config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_wezterm.lua:
    src: wezterm.lua
    dst: ~/.wezterm.lua
  d_fish:
    src: config/fish
    dst: ~/.config/fish
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_zellij:
    src: config/zellij
    dst: ~/.config/zellij
profiles:
  gil-kubuntu:
    dotfiles:
    - f_wezterm.lua
    - d_fish
    - d_nvim
    - d_zellij
